/** @format */

import { cn } from "@/lib/utils";
// import "./globals.css";
import "./global.css";
import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import Navbar from "@/components/Navbar";

const lexend = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Skill Whiz",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={cn(lexend.className, "antialiased min-h-screen ")}>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
